const questions = [
{ text: 'What is the capital of Burkina Faso?',
    answer: 'Ouagadougou',
    op1: 'Mexico City',
    op2: 'Wauwatosa',
    op3: 'Tahiti',
},

{ text: 'Who is the first person to win two Nobel Prizes?',
    answer: 'Marie Curie',
    op1: 'Albert Einstein',
    op2: 'Ernest Hemingway',
    op3: 'Eichiro Oda',
},

{ text: 'What country did the United States invade following the September 11th attacks?',
    answer: 'Afghanistan',
    op1: 'Iran',
    op2: 'Iraq',
    op3: 'Saudi Arabia',
},

{text: 'How much is a human life worth?' ,
    answer:'Indeterminate',
    op1: '$17/hour',
    op2: 'As much as another',
    op3: 'milk',
},
{text: 'What is the Earliest literate civilization in human history?' ,
    answer: 'Mesopotamia',
    op1: 'Ancient Egypt',
    op2: 'Athens',
    op3: 'Indus River Valley Civilization',
},

{ text: 'What One Piece character said "Justice will prevail you say? But of course it will, Whoever wins (this war) becomes justice"?',
    answer: 'Donquixote Doflamingo',
    op1: 'Gol D. Roger',
    op2: 'Minato Uzumaki',
    op3: 'George Graham',
},

{ text: "What is the Spanish word 'Puto' mean?",
    answer: 'Male Prostitute',
    op1: 'Female Dog',
    op2: 'Homosexual',
    op3: 'No mames guey',
},

{ text: 'Are you a good person?',
    answer: 'No',
    op1: 'Yes',
    op2: 'I hope so',
    op3: 'I try to be',
},

{ text: 'Where in the human body does oxygenation of the blood occur?',
    answer: 'Alveoli',
    op1: 'Lebanon',
    op2: 'Vena Cava',
    op3: 'Mitochondria, the powerhouse of the cell',
},

{ text: 'Is it better to live as a kind and rightous slave to wretched men, or a cruel and callous deviant against those same men?',
    answer:'   ',
    op1: 'the former',
    op2: 'the latter',
    op3: 'neither',
},

{ text: 'What is the square root of 987654321?',
    answer: '31426.9680529',
    op1: '29487.445761',
    op2: '3.14159256',
    op3: '444444.1',
},

{ text: 'Do you ignore any evils?',
    answer:'Yes',
    op1: 'No',
    op2: 'I try not to',
    op3: 'Sometimes',
},

{ text: 'Are you better than the others?',
    answer:'No',
    op1: 'Yes',
    op2: 'Sometimes',
    op3: '   ',
},

{ text:'Is one responsible for the sins of those they support?',
    answer:'   ',
    op1: 'Yes',
    op2: 'Sometimes',
    op3: 'No',
},

{ text: 'How did Socrates die',
answer: 'Executed for impiety',
op1: 'Executed by democracy',
op2: 'Suicide',
op3: 'Killed as a casualty of the Peloponnesian War',
},

{ text: 'What is the patron deity of the United States?',
    answer: 'Money',
    op1: 'Sex',
    op2: 'The self',
    op3: 'Jesus Christ',
},

{ text: 'Are domesticated animals slave races existing solely for our pleasure?',
    answer:'Yes',
    op1: 'No',
    op2: 'Sometimes',
    op3: 'milk',
},

{ text: 'Is it not easy to rationalize excuses?',
    answer:'Yes',
    op1: 'Si',
    op2: 'Indeed',
    op3: 'Aye',
},

{ text: 'What is it that one ought to do?',
    answer:'I do not know',
    op1:'Live for self pleasure',
    op2:'Live to leave behind a legacy',
    op3:'There is no meaning in anything',
},

{ text: 'Do human beings deserve to exist?',
    answer: 'Maybe; what is it that designates deserved existence?',
    op1:'No, for we are the only species who arre willfully ignorant and actively cruel',
    op2:"Yes, for we are in God's likeness and are able to do utopic awesome things",
    op3:'I hope so',
},
{ text: 'Are you a good being?',
    answer:"I try to be",
    op1: 'Yes',
    op2: 'No',
    op3: 'I do not know',
},

{ text: 'I know this was unpleasant. Or perhaps it was mildly amusing to you.',
    answer:'If you made it this far, know I am afraid. It feels as though our generation has had our ignorance stolen from us.',
    op1: 'Ignorance is Bliss',
    op2: 'We are condemned to knowledge and all its terror',
    op3: 'In a world full of our lesser peers and predecessors',
},

{  text: "What should I do? What must be done? What is 'good'?",

},
]
