const questions = [
{ text: 'What is the capital of Burkina Faso?',
    answer: 'Ouagadougou',
    op1: 'Mexico City',
    op2: 'Wauwatosa',
    op3: 'Tahiti',
},

{ text: 'Who is the first person to win two Nobel Prizes?',
    answer: 'Marie Curie',
    op1: 'Albert Einstein',
    op2: 'Ernest Hemingway',
    op3: 'Eichiro Oda',
},

{ text: 'What country did the United States invade following the September 11th attacks?',
    answer: 'Afghanistan',
    op1: 'Iran',
    op2: 'Iraq',
    op3: 'Saudi Arabia',
},

{text: 'How much is a human life worth?' ,
    answer:'Indeterminate',
    op1: '$17/hour',
    op2: 'As much as another',
    op3: 'milk',
},
{text: 'What is the Earliest literate civilization in human history?' ,
    answer: 'Mesopotamia',
    op1: 'Ancient Egypt',
    op2: 'Athens',
    op3: 'Indus River Valley Civilization',
},

{ text: 'What One Piece character said "Justice will prevail you say? But of course it will, Whoever wins (this war) becomes justice"?',
    answer: 'Donquixote Doflamingo',
    op1: 'Gol D. Roger',
    op2: 'Minato Uzumaki',
    op3: 'George Graham',
},

{ text: "What is the Spanish word 'Puto' mean?",
    answer: 'Male Prostitute',
    op1: 'Female Dog',
    op2: 'Homosexual',
    op3: 'No mames guey',
},

{ text: 'Are you a good person?',
    answer: 'No',
    op1: 'Yes',
    op2: 'I hope so',
    op3: 'I try to be',
},

{ text: 'Where in the human body does oxygenation of the blood occur?',
    answer: 'Alveoli',
    op1: 'Lebanon',
    op2: 'Vena Cava',
    op3: 'Mitochondria, the powerhouse of the cell',
},

{ text: 'Is it better to live as a kind and rightous slave to wretched men, or a cruel and callous deviant against those same men?',
    answer:'   ',
    op1: 'the former',
    op2: 'the latter',
    op3: 'neither',
},

{ text: 'What is the square root of 987654321?',
    answer: '31426.9680529',
    op1: '29487.445761',
    op2: '3.14159256',
    op3: 'milk',
},

{ text: 'Do you ignore any evils?',
    answer:'Yes',
    op1: 'No',
    op2: 'I try not to',
    op3: 'Sometimes',
},

{ text: 'Are you better than the others?',
    answer:'No',
    op1: 'Yes',
    op2: 'Sometimes',
    op3: '   ',
},

{ text:'Is one responsible for the sins of those they support?',
    answer:'   ',
    op1: 'Yes',
    op2: 'Sometimes',
    op3: 'No',
},

{ text: 'How did Socrates die',
answer: 'Executed for impiety',
op1: 'Executed by democracy',
op2: 'Suicide',
op3: 'Killed as a casualty during the Peloponnesian War',
},

{ text: 'What is the patron deity of the United States?',
    answer: 'Money',
    op1: 'Sex',
    op2: 'The self',
    op3: 'Jesus Christ',
},

{ text: 'Are domesticated animals slave races existing solely for our pleasure?',
    answer:'Yes',
    op1: 'No',
    op2: 'Sometimes',
    op3: 'milk',
},

{ text: 'Is it not easy to rationalize excuses?',
    answer:'Yes',
    op1: 'Yes',
    op2: 'Yes',
    op3: 'Yes',
},

{ text: 'Are you a good being?',
    answer:'   ',
    op1: '   ',
    op2: '   ',
    op3: '   ',
},
]
// 'Of course you think so.'